all: test1 test2 test3
test1:
	mkdir -p build
	clang++-8 -std=c++14 -Wall test1.cpp -o build/test1

test2:
	mkdir -p build
	clang++-8 -std=c++14 -Wall test2.cpp -o build/test2

test3:
	mkdir -p build
	clang++-8 -std=c++14 -Wall test3.cpp -o build/test3

clear:
	rm -f *.o
