all: test1 test2 test3
test1:
	clang++-8 -std=c++14 -Wall test1.cpp -o test1

test2:
	clang++-8 -std=c++14 -Wall test2.cpp -o test2

test3:
	clang++-8 -std=c++14 -Wall test3.cpp -o test3

clear:
	rm -f *.o
